### ISSUE TITLE
CEASE AND DESIST ALL COPYRIGHT INFRINGEMENT

### ISSUE THREAD

**Issue by xamphyx** [leotm/ProductSans-Regular#1]
I am writing to notify you that your unlawful copying of the "[Download Product Sans Font by Google | Xamphyx](http://www.xamphyx.com/product-sans-download.html)" web page infringes upon my exclusive copyrights. Accordingly, you are hereby directed to CEASE AND DESIST ALL COPYRIGHT INFRINGEMENT.

**Comment by leotm** [comment]
Hey @xamphyx my apologies, any content from your web page has been removed.
